
#### **Data**

This data set is from [Our World in Data](https://ourworldindata.org/causes-of-death). 
It contained the mortality rate of various existing diseases for each country around 
the world and each year.


#### **Purpose**

As the countries shift their focus onto the COVID-19 pandemic, this may shadow the other existing diseases.

Therefore the purpose of this app is to:

1. Highlight the existing disease that impacts countries around the world,
2. Allow the healthcare professional easier access to the disease information, and
3. Spread awareness about the disease in different regions.

The app used an interactive map to allow the user to see how different diseases impact different countries (e.g. the highest cause of death in the country). The second and last panel used the interactive components to allow the user to decide which information is relevant to them. The data is presented using the time series plot, table, bar plot, and map for an easier understanding of the data.


#### **Creator**

Krisanat Anukarnsakulchularp (kanu0003@student.monash.edu)

<details>
<summary>Session information</summary>
```{r, echo = FALSE}
sessioninfo::session_info()
```
</details>
